name: auto-update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - merge-develop
    types:
      - completed
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install
        run: pip install -r requirements.txt
      
      # - name: Clean
      #   run: rm dst/*

      - name: Fetch
        run: python3 fetch.py
      
      - name: Compress
        run: gzip -9 -k -f dst/*.txt
      
      - name: Check
        run: ls -lh dst

      - name: Update date
        run: |
          sed -e "s/^\(Last Updated: \).*/\1$(date --iso-8601=seconds)/" -i README.md && git add README.md

      - name: Commit
        run: |
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if ! git diff --cached --quiet; then
            git commit -m "auto update"
            git push
          else
            echo "No changes to commit"
          fi
