name: merge-develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
    
      - name: Merge
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git merge --strategy-option=theirs develop
          git push
