name: merge-develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
    
      - name: Merge
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git merge --strategy-option=theirs origin/develop -m "auto merge"
          git push
