name: overwrite-release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  force-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      
      - name: Force push to release branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
          force: true
