name: Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: install
        run: pip install -r requirements.txt

      - name: fetch
        run: python3 fetch.py
      
      - name: check
        run: ls -lh dst

      - name: update date
        run: 'sed -e "s/^\(last updated: \).*/\1$(date --iso-8601=seconds)/" -i README.md'

      - name: commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add dst README.md
          git commit -m "update"
          git push
