name: Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: fetch
        run: python3 fetch.py

      - name: update date
        run: 'sed -e "s/^(last updated: ).*/\1$(date --iso-8601=seconds)/" -i README.md'

      - name: commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git commit -am "update"
          git push
